[2024-08-19T07:16:10.389+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: test_email_dag.send_email manual__2024-08-19T07:16:07.456393+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
