[2024-08-13T16:09:32.450+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-13T16:09:32.485+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Weather_Data_Extraction.check_inserted backfill__2024-02-15T00:00:00+00:00 [queued]>
[2024-08-13T16:09:32.856+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Weather_Data_Extraction.check_inserted backfill__2024-02-15T00:00:00+00:00 [queued]>
[2024-08-13T16:09:32.857+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-08-13T16:09:32.891+0000] {taskinstance.py:2330} INFO - Executing <Task(BranchPythonOperator): check_inserted> on 2024-02-15 00:00:00+00:00
[2024-08-13T16:09:32.913+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1043) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-13T16:09:32.919+0000] {standard_task_runner.py:63} INFO - Started process 1060 to run task
[2024-08-13T16:09:32.939+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Weather_Data_Extraction', 'check_inserted', 'backfill__2024-02-15T00:00:00+00:00', '--job-id', '196', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/Data_Weather_Extraction.py', '--cfg-path', '/tmp/tmps_31ftdh']
[2024-08-13T16:09:32.948+0000] {standard_task_runner.py:91} INFO - Job 196: Subtask check_inserted
[2024-08-13T16:09:33.001+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-08-13T16:09:33.090+0000] {task_command.py:426} INFO - Running <TaskInstance: Weather_Data_Extraction.check_inserted backfill__2024-02-15T00:00:00+00:00 [running]> on host ubuntu
[2024-08-13T16:09:33.300+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Ducky' AIRFLOW_CTX_DAG_ID='Weather_Data_Extraction' AIRFLOW_CTX_TASK_ID='check_inserted' AIRFLOW_CTX_EXECUTION_DATE='2024-02-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='backfill__2024-02-15T00:00:00+00:00'
[2024-08-13T16:09:33.302+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-13T16:09:33.330+0000] {baseoperator.py:400} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-08-13T16:09:33.332+0000] {logging_mixin.py:188} INFO - 2024-02-15
[2024-08-13T16:09:33.333+0000] {logging_mixin.py:188} INFO - <class 'pendulum.date.Date'>
[2024-08-13T16:09:33.368+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn_raw' for task execution.
[2024-08-13T16:09:33.371+0000] {connection.py:399} INFO - Snowflake Connector for Python Version: 3.10.1, Python Version: 3.12.4, Platform: Linux-5.15.153.1-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2024-08-13T16:09:33.372+0000] {connection.py:1239} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-08-13T16:09:34.426+0000] {logging_mixin.py:188} INFO - Connected Successfully!
[2024-08-13T16:09:34.427+0000] {logging_mixin.py:188} INFO - 
        SELECT MAX(INPUT_DATE) FROM RAW_WEATHER_DATA;
    
[2024-08-13T16:09:34.561+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-08-13T16:09:34.563+0000] {logging_mixin.py:188} INFO - 2024-08-12
[2024-08-13T16:09:34.564+0000] {logging_mixin.py:188} INFO - <class 'pendulum.date.Date'>
[2024-08-13T16:09:34.565+0000] {connection.py:762} INFO - closed
[2024-08-13T16:09:34.649+0000] {connection.py:768} INFO - No async queries seem to be running, deleting session
[2024-08-13T16:09:34.737+0000] {logging_mixin.py:188} INFO - no_new_data task will execute
[2024-08-13T16:09:34.739+0000] {python.py:237} INFO - Done. Returned value was: no_new_data
[2024-08-13T16:09:34.740+0000] {branch.py:36} INFO - Branch into no_new_data
[2024-08-13T16:09:34.740+0000] {skipmixin.py:178} INFO - Following branch no_new_data
[2024-08-13T16:09:34.765+0000] {skipmixin.py:246} INFO - Skipping tasks [('invoke_lambda_task', -1)]
[2024-08-13T16:09:34.804+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-13T16:09:34.850+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Weather_Data_Extraction, task_id=check_inserted, run_id=backfill__2024-02-15T00:00:00+00:00, execution_date=20240215T000000, start_date=20240813T160932, end_date=20240813T160934
[2024-08-13T16:09:34.912+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-08-13T16:09:34.982+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-08-13T16:09:34.989+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-08-14T04:22:54.798+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-14T04:22:54.842+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Weather_Data_Extraction.check_inserted backfill__2024-02-15T00:00:00+00:00 [queued]>
[2024-08-14T04:22:54.863+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Weather_Data_Extraction.check_inserted backfill__2024-02-15T00:00:00+00:00 [queued]>
[2024-08-14T04:22:54.864+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-08-14T04:22:55.034+0000] {taskinstance.py:2330} INFO - Executing <Task(BranchPythonOperator): check_inserted> on 2024-02-15 00:00:00+00:00
[2024-08-14T04:22:55.048+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2139) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-14T04:22:55.052+0000] {standard_task_runner.py:63} INFO - Started process 2141 to run task
[2024-08-14T04:22:55.054+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Weather_Data_Extraction', 'check_inserted', 'backfill__2024-02-15T00:00:00+00:00', '--job-id', '540', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/Data_Weather_Extraction.py', '--cfg-path', '/tmp/tmp_pg73lys']
[2024-08-14T04:22:55.061+0000] {standard_task_runner.py:91} INFO - Job 540: Subtask check_inserted
[2024-08-14T04:22:55.173+0000] {task_command.py:426} INFO - Running <TaskInstance: Weather_Data_Extraction.check_inserted backfill__2024-02-15T00:00:00+00:00 [running]> on host ubuntu
[2024-08-14T04:22:55.384+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Ducky' AIRFLOW_CTX_DAG_ID='Weather_Data_Extraction' AIRFLOW_CTX_TASK_ID='check_inserted' AIRFLOW_CTX_EXECUTION_DATE='2024-02-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='backfill__2024-02-15T00:00:00+00:00'
[2024-08-14T04:22:55.388+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-14T04:22:55.414+0000] {baseoperator.py:400} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-08-14T04:22:55.416+0000] {logging_mixin.py:188} INFO - 2024-02-15
[2024-08-14T04:22:55.417+0000] {logging_mixin.py:188} INFO - <class 'pendulum.date.Date'>
[2024-08-14T04:22:55.438+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn_raw' for task execution.
[2024-08-14T04:22:55.440+0000] {connection.py:399} INFO - Snowflake Connector for Python Version: 3.10.1, Python Version: 3.12.4, Platform: Linux-5.15.153.1-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2024-08-14T04:22:55.441+0000] {connection.py:1239} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-08-14T04:22:56.345+0000] {logging_mixin.py:188} INFO - Connected Successfully!
[2024-08-14T04:22:56.346+0000] {logging_mixin.py:188} INFO - 
        SELECT MAX(INPUT_DATE) FROM RAW_WEATHER_DATA;
    
[2024-08-14T04:22:56.476+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-08-14T04:22:56.478+0000] {logging_mixin.py:188} INFO - 2024-02-08
[2024-08-14T04:22:56.480+0000] {logging_mixin.py:188} INFO - <class 'pendulum.date.Date'>
[2024-08-14T04:22:56.481+0000] {connection.py:762} INFO - closed
[2024-08-14T04:22:56.574+0000] {connection.py:768} INFO - No async queries seem to be running, deleting session
[2024-08-14T04:22:56.686+0000] {logging_mixin.py:188} INFO - invoke_lambda_task task will execute
[2024-08-14T04:22:56.689+0000] {python.py:237} INFO - Done. Returned value was: invoke_lambda_task
[2024-08-14T04:22:56.691+0000] {branch.py:36} INFO - Branch into invoke_lambda_task
[2024-08-14T04:22:56.693+0000] {skipmixin.py:178} INFO - Following branch invoke_lambda_task
[2024-08-14T04:22:56.729+0000] {skipmixin.py:246} INFO - Skipping tasks [('no_new_data', -1)]
[2024-08-14T04:22:56.775+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-14T04:22:56.804+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Weather_Data_Extraction, task_id=check_inserted, run_id=backfill__2024-02-15T00:00:00+00:00, execution_date=20240215T000000, start_date=20240814T042254, end_date=20240814T042256
[2024-08-14T04:22:56.840+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-08-14T04:22:56.883+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-08-14T04:22:56.890+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
