[2024-08-16T09:45:31.600+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-16T09:45:31.800+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Weather_Data_Extraction.invoke_lambda_task backfill__2024-08-13T00:00:00+00:00 [queued]>
[2024-08-16T09:45:31.821+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Weather_Data_Extraction.invoke_lambda_task backfill__2024-08-13T00:00:00+00:00 [queued]>
[2024-08-16T09:45:31.823+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-08-16T09:45:31.846+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): invoke_lambda_task> on 2024-08-13 00:00:00+00:00
[2024-08-16T09:45:31.855+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1561) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-16T09:45:31.859+0000] {standard_task_runner.py:63} INFO - Started process 1563 to run task
[2024-08-16T09:45:31.861+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Weather_Data_Extraction', 'invoke_lambda_task', 'backfill__2024-08-13T00:00:00+00:00', '--job-id', '1181', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/Data_Weather_Extraction.py', '--cfg-path', '/tmp/tmppbfnmqbs']
[2024-08-16T09:45:31.866+0000] {standard_task_runner.py:91} INFO - Job 1181: Subtask invoke_lambda_task
[2024-08-16T09:45:31.969+0000] {task_command.py:426} INFO - Running <TaskInstance: Weather_Data_Extraction.invoke_lambda_task backfill__2024-08-13T00:00:00+00:00 [running]> on host ubuntu
[2024-08-16T09:45:32.138+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Ducky' AIRFLOW_CTX_DAG_ID='Weather_Data_Extraction' AIRFLOW_CTX_TASK_ID='invoke_lambda_task' AIRFLOW_CTX_EXECUTION_DATE='2024-08-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='backfill__2024-08-13T00:00:00+00:00'
[2024-08-16T09:45:32.140+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-16T09:45:32.184+0000] {logging_mixin.py:188} INFO - Data_Weather-20240813.csv
[2024-08-16T09:45:32.185+0000] {logging_mixin.py:188} INFO - 2024/08/13
[2024-08-16T09:45:32.186+0000] {logging_mixin.py:188} INFO - {"execution_date": "2024/08/13", "file_name": "Data_Weather-20240813.csv"}
[2024-08-16T09:45:32.187+0000] {logging_mixin.py:188} INFO - https://eyzyhdwl8l.execute-api.ap-southeast-2.amazonaws.com/dev?execution_date=2024/08/13&file_name=Data_Weather-20240813.csv
[2024-08-16T09:45:33.910+0000] {logging_mixin.py:188} INFO - Lambda function invoked successfully.
[2024-08-16T09:45:33.910+0000] {logging_mixin.py:188} INFO - Response: {'errorMessage': "Execution failed on sql 'SELECT * FROM SCD_CITY WHERE PROVINCE_CODE = 44 AND DBT_VALID_TO IS NULL ORDER BY CITY_CODE': 002003 (42S02): SQL compilation error:\nObject 'SCD_CITY' does not exist or not authorized.", 'errorType': 'DatabaseError', 'requestId': 'e1050fbb-fe5e-4461-ab0d-c960ade1fd54', 'stackTrace': ['  File "/var/task/lambda_function.py", line 108, in lambda_handler\n    result_df = extract_weather_data(file_name, execution_date)\n', '  File "/var/task/lambda_function.py", line 30, in extract_weather_data\n    result_set = pd.read_sql(query, con= conn)\n', '  File "/opt/python/pandas/io/sql.py", line 706, in read_sql\n    return pandas_sql.read_query(\n', '  File "/opt/python/pandas/io/sql.py", line 2738, in read_query\n    cursor = self.execute(sql, params)\n', '  File "/opt/python/pandas/io/sql.py", line 2686, in execute\n    raise ex from exc\n']}
[2024-08-16T09:45:33.913+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-08-16T09:45:33.914+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-16T09:45:33.924+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Weather_Data_Extraction, task_id=invoke_lambda_task, run_id=backfill__2024-08-13T00:00:00+00:00, execution_date=20240813T000000, start_date=20240816T094531, end_date=20240816T094533
[2024-08-16T09:45:33.966+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-08-16T09:45:34.001+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-08-16T09:45:34.004+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-08-16T10:09:10.416+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-16T10:09:10.614+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Weather_Data_Extraction.invoke_lambda_task backfill__2024-08-13T00:00:00+00:00 [queued]>
[2024-08-16T10:09:10.628+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Weather_Data_Extraction.invoke_lambda_task backfill__2024-08-13T00:00:00+00:00 [queued]>
[2024-08-16T10:09:10.630+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-08-16T10:09:10.652+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): invoke_lambda_task> on 2024-08-13 00:00:00+00:00
[2024-08-16T10:09:10.661+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2327) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-16T10:09:10.663+0000] {standard_task_runner.py:63} INFO - Started process 2329 to run task
[2024-08-16T10:09:10.664+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Weather_Data_Extraction', 'invoke_lambda_task', 'backfill__2024-08-13T00:00:00+00:00', '--job-id', '1266', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/Data_Weather_Extraction.py', '--cfg-path', '/tmp/tmp03h4ap9h']
[2024-08-16T10:09:10.668+0000] {standard_task_runner.py:91} INFO - Job 1266: Subtask invoke_lambda_task
[2024-08-16T10:09:10.722+0000] {task_command.py:426} INFO - Running <TaskInstance: Weather_Data_Extraction.invoke_lambda_task backfill__2024-08-13T00:00:00+00:00 [running]> on host ubuntu
[2024-08-16T10:09:10.822+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Ducky' AIRFLOW_CTX_DAG_ID='Weather_Data_Extraction' AIRFLOW_CTX_TASK_ID='invoke_lambda_task' AIRFLOW_CTX_EXECUTION_DATE='2024-08-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='backfill__2024-08-13T00:00:00+00:00'
[2024-08-16T10:09:10.824+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-16T10:09:10.852+0000] {logging_mixin.py:188} INFO - Data_Weather-20240813.csv
[2024-08-16T10:09:10.852+0000] {logging_mixin.py:188} INFO - 2024/08/13
[2024-08-16T10:09:10.853+0000] {logging_mixin.py:188} INFO - {"execution_date": "2024/08/13", "file_name": "Data_Weather-20240813.csv"}
[2024-08-16T10:09:10.853+0000] {logging_mixin.py:188} INFO - https://eyzyhdwl8l.execute-api.ap-southeast-2.amazonaws.com/dev?execution_date=2024/08/13&file_name=Data_Weather-20240813.csv
[2024-08-16T10:09:40.524+0000] {logging_mixin.py:188} INFO - Failed to invoke Lambda function.
[2024-08-16T10:09:40.525+0000] {logging_mixin.py:188} INFO - Response: {"message": "Endpoint request timed out"}
[2024-08-16T10:09:40.531+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-08-16T10:09:40.534+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-16T10:09:40.557+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Weather_Data_Extraction, task_id=invoke_lambda_task, run_id=backfill__2024-08-13T00:00:00+00:00, execution_date=20240813T000000, start_date=20240816T100910, end_date=20240816T100940
[2024-08-16T10:09:40.619+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-08-16T10:09:40.652+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-08-16T10:09:40.655+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
