[2024-08-13T16:08:04.030+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-13T16:08:04.070+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Weather_Data_Extraction.copy_csv_to_table backfill__2024-01-01T00:00:00+00:00 [queued]>
[2024-08-13T16:08:04.296+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Weather_Data_Extraction.copy_csv_to_table backfill__2024-01-01T00:00:00+00:00 [queued]>
[2024-08-13T16:08:04.298+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-08-13T16:08:04.328+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): copy_csv_to_table> on 2024-01-01 00:00:00+00:00
[2024-08-13T16:08:04.342+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=816) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-13T16:08:04.349+0000] {standard_task_runner.py:63} INFO - Started process 818 to run task
[2024-08-13T16:08:04.346+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Weather_Data_Extraction', 'copy_csv_to_table', 'backfill__2024-01-01T00:00:00+00:00', '--job-id', '121', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/Data_Weather_Extraction.py', '--cfg-path', '/tmp/tmp7plkou_0']
[2024-08-13T16:08:04.352+0000] {standard_task_runner.py:91} INFO - Job 121: Subtask copy_csv_to_table
[2024-08-13T16:08:04.379+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-08-13T16:08:04.452+0000] {task_command.py:426} INFO - Running <TaskInstance: Weather_Data_Extraction.copy_csv_to_table backfill__2024-01-01T00:00:00+00:00 [running]> on host ubuntu
[2024-08-13T16:08:04.631+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Ducky' AIRFLOW_CTX_DAG_ID='Weather_Data_Extraction' AIRFLOW_CTX_TASK_ID='copy_csv_to_table' AIRFLOW_CTX_EXECUTION_DATE='2024-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='backfill__2024-01-01T00:00:00+00:00'
[2024-08-13T16:08:04.636+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-13T16:08:04.697+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn_raw' for task execution.
[2024-08-13T16:08:04.700+0000] {connection.py:399} INFO - Snowflake Connector for Python Version: 3.10.1, Python Version: 3.12.4, Platform: Linux-5.15.153.1-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2024-08-13T16:08:04.702+0000] {connection.py:1239} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-08-13T16:08:05.784+0000] {logging_mixin.py:188} INFO - Connected to Snowflake Successfully!
[2024-08-13T16:08:05.834+0000] {logging_mixin.py:188} INFO - s3://s3-poc-data-marketplace/Weather_Data/Data_Weather-20240101.csv
[2024-08-13T16:08:05.836+0000] {logging_mixin.py:188} INFO - 
        COPY INTO RAW_WEATHER_DATA
        FROM 's3://s3-poc-data-marketplace/Weather_Data/Data_Weather-20240101.csv'
        CREDENTIALS = (AWS_KEY_ID='AKIA5FTZBUCGQ4SERYPG' AWS_SECRET_KEY='***')
        FILE_FORMAT = (TYPE = 'CSV', DATE_FORMAT = 'YYYY-MM-DD', SKIP_HEADER = 1, ENCODING='UTF8')
        RETURN_FAILED_ONLY = TRUE;
        
[2024-08-13T16:08:07.355+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-08-13T16:08:07.357+0000] {connection.py:762} INFO - closed
[2024-08-13T16:08:07.450+0000] {connection.py:768} INFO - No async queries seem to be running, deleting session
[2024-08-13T16:08:07.551+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-08-13T16:08:07.552+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-13T16:08:07.567+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Weather_Data_Extraction, task_id=copy_csv_to_table, run_id=backfill__2024-01-01T00:00:00+00:00, execution_date=20240101T000000, start_date=20240813T160804, end_date=20240813T160807
[2024-08-13T16:08:07.629+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-08-13T16:08:07.655+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-13T16:08:07.659+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-08-14T02:45:49.905+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-14T02:45:49.928+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Weather_Data_Extraction.copy_csv_to_table backfill__2024-01-01T00:00:00+00:00 [queued]>
[2024-08-14T02:45:50.073+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Weather_Data_Extraction.copy_csv_to_table backfill__2024-01-01T00:00:00+00:00 [queued]>
[2024-08-14T02:45:50.074+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-08-14T02:45:50.091+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): copy_csv_to_table> on 2024-01-01 00:00:00+00:00
[2024-08-14T02:45:50.098+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=278) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-14T02:45:50.100+0000] {standard_task_runner.py:63} INFO - Started process 280 to run task
[2024-08-14T02:45:50.100+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Weather_Data_Extraction', 'copy_csv_to_table', 'backfill__2024-01-01T00:00:00+00:00', '--job-id', '327', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/Data_Weather_Extraction.py', '--cfg-path', '/tmp/tmpi8bymyym']
[2024-08-14T02:45:50.104+0000] {standard_task_runner.py:91} INFO - Job 327: Subtask copy_csv_to_table
[2024-08-14T02:45:50.155+0000] {task_command.py:426} INFO - Running <TaskInstance: Weather_Data_Extraction.copy_csv_to_table backfill__2024-01-01T00:00:00+00:00 [running]> on host ubuntu
[2024-08-14T02:45:50.260+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Ducky' AIRFLOW_CTX_DAG_ID='Weather_Data_Extraction' AIRFLOW_CTX_TASK_ID='copy_csv_to_table' AIRFLOW_CTX_EXECUTION_DATE='2024-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='backfill__2024-01-01T00:00:00+00:00'
[2024-08-14T02:45:50.264+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-14T02:45:50.291+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn_raw' for task execution.
[2024-08-14T02:45:50.293+0000] {connection.py:399} INFO - Snowflake Connector for Python Version: 3.10.1, Python Version: 3.12.4, Platform: Linux-5.15.153.1-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2024-08-14T02:45:50.294+0000] {connection.py:1239} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-08-14T02:45:51.687+0000] {logging_mixin.py:188} INFO - Connected to Snowflake Successfully!
[2024-08-14T02:45:51.703+0000] {logging_mixin.py:188} INFO - s3://s3-poc-data-marketplace/Weather_Data/Data_Weather-20240101.csv
[2024-08-14T02:45:51.703+0000] {logging_mixin.py:188} INFO - 
        COPY INTO RAW_WEATHER_DATA
        FROM 's3://s3-poc-data-marketplace/Weather_Data/Data_Weather-20240101.csv'
        CREDENTIALS = (AWS_KEY_ID='AKIA5FTZBUCGQ4SERYPG' AWS_SECRET_KEY='***')
        FILE_FORMAT = (TYPE = 'CSV', DATE_FORMAT = 'YYYY-MM-DD', SKIP_HEADER = 1, ENCODING='UTF8')
        RETURN_FAILED_ONLY = TRUE;
        
[2024-08-14T02:45:53.439+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-08-14T02:45:53.441+0000] {connection.py:762} INFO - closed
[2024-08-14T02:45:53.536+0000] {connection.py:768} INFO - No async queries seem to be running, deleting session
[2024-08-14T02:45:53.642+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-08-14T02:45:53.646+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-14T02:45:53.672+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Weather_Data_Extraction, task_id=copy_csv_to_table, run_id=backfill__2024-01-01T00:00:00+00:00, execution_date=20240101T000000, start_date=20240814T024549, end_date=20240814T024553
[2024-08-14T02:45:53.733+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-08-14T02:45:53.753+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-14T02:45:53.756+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
