[2024-08-16T09:17:03.912+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-16T09:17:04.101+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Weather_Data_Extraction.invoke_lambda_task backfill__2024-08-14T00:00:00+00:00 [queued]>
[2024-08-16T09:17:04.124+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Weather_Data_Extraction.invoke_lambda_task backfill__2024-08-14T00:00:00+00:00 [queued]>
[2024-08-16T09:17:04.125+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-08-16T09:17:04.156+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): invoke_lambda_task> on 2024-08-14 00:00:00+00:00
[2024-08-16T09:17:04.167+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1071) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-16T09:17:04.170+0000] {standard_task_runner.py:63} INFO - Started process 1073 to run task
[2024-08-16T09:17:04.171+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Weather_Data_Extraction', 'invoke_lambda_task', 'backfill__2024-08-14T00:00:00+00:00', '--job-id', '1155', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/Data_Weather_Extraction.py', '--cfg-path', '/tmp/tmpfw8amqn6']
[2024-08-16T09:17:04.175+0000] {standard_task_runner.py:91} INFO - Job 1155: Subtask invoke_lambda_task
[2024-08-16T09:17:04.263+0000] {task_command.py:426} INFO - Running <TaskInstance: Weather_Data_Extraction.invoke_lambda_task backfill__2024-08-14T00:00:00+00:00 [running]> on host ubuntu
[2024-08-16T09:17:04.381+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Ducky' AIRFLOW_CTX_DAG_ID='Weather_Data_Extraction' AIRFLOW_CTX_TASK_ID='invoke_lambda_task' AIRFLOW_CTX_EXECUTION_DATE='2024-08-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='backfill__2024-08-14T00:00:00+00:00'
[2024-08-16T09:17:04.384+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-16T09:17:04.433+0000] {logging_mixin.py:188} INFO - Data_Weather-20240814.csv
[2024-08-16T09:17:04.434+0000] {logging_mixin.py:188} INFO - 2024/08/14
[2024-08-16T09:17:04.436+0000] {logging_mixin.py:188} INFO - {"execution_date": "2024/08/14", "file_name": "Data_Weather-20240814.csv"}
[2024-08-16T09:17:04.437+0000] {logging_mixin.py:188} INFO - https://eyzyhdwl8l.execute-api.ap-southeast-2.amazonaws.com/dev?execution_date=2024/08/14&file_name=Data_Weather-20240814.csv
[2024-08-16T09:17:12.322+0000] {logging_mixin.py:188} INFO - Lambda function invoked successfully.
[2024-08-16T09:17:12.323+0000] {logging_mixin.py:188} INFO - Response: {'errorMessage': "Execution failed on sql 'SELECT * FROM SCD_CITY WHERE PROVINCE_CODE = 44 AND DBT_VALID_TO IS NULL ORDER BY CITY_CODE': 002003 (42S02): SQL compilation error:\nObject 'SCD_CITY' does not exist or not authorized.", 'errorType': 'DatabaseError', 'requestId': '0bb4fc8e-f270-4168-a089-deeb444ea70f', 'stackTrace': ['  File "/var/task/lambda_function.py", line 108, in lambda_handler\n    result_df = extract_weather_data(file_name, execution_date)\n', '  File "/var/task/lambda_function.py", line 30, in extract_weather_data\n    result_set = pd.read_sql(query, con= conn)\n', '  File "/opt/python/pandas/io/sql.py", line 706, in read_sql\n    return pandas_sql.read_query(\n', '  File "/opt/python/pandas/io/sql.py", line 2738, in read_query\n    cursor = self.execute(sql, params)\n', '  File "/opt/python/pandas/io/sql.py", line 2686, in execute\n    raise ex from exc\n']}
[2024-08-16T09:17:12.325+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-08-16T09:17:12.326+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-16T09:17:12.335+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Weather_Data_Extraction, task_id=invoke_lambda_task, run_id=backfill__2024-08-14T00:00:00+00:00, execution_date=20240814T000000, start_date=20240816T091704, end_date=20240816T091712
[2024-08-16T09:17:12.398+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-08-16T09:17:12.460+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-08-16T09:17:12.466+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-08-16T09:48:01.764+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-16T09:48:01.949+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Weather_Data_Extraction.invoke_lambda_task backfill__2024-08-14T00:00:00+00:00 [queued]>
[2024-08-16T09:48:01.961+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Weather_Data_Extraction.invoke_lambda_task backfill__2024-08-14T00:00:00+00:00 [queued]>
[2024-08-16T09:48:01.962+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-08-16T09:48:01.980+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): invoke_lambda_task> on 2024-08-14 00:00:00+00:00
[2024-08-16T09:48:01.987+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1694) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-16T09:48:01.989+0000] {standard_task_runner.py:63} INFO - Started process 1700 to run task
[2024-08-16T09:48:01.990+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Weather_Data_Extraction', 'invoke_lambda_task', 'backfill__2024-08-14T00:00:00+00:00', '--job-id', '1198', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/Data_Weather_Extraction.py', '--cfg-path', '/tmp/tmps1rfwfsg']
[2024-08-16T09:48:01.992+0000] {standard_task_runner.py:91} INFO - Job 1198: Subtask invoke_lambda_task
[2024-08-16T09:48:02.042+0000] {task_command.py:426} INFO - Running <TaskInstance: Weather_Data_Extraction.invoke_lambda_task backfill__2024-08-14T00:00:00+00:00 [running]> on host ubuntu
[2024-08-16T09:48:02.158+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Ducky' AIRFLOW_CTX_DAG_ID='Weather_Data_Extraction' AIRFLOW_CTX_TASK_ID='invoke_lambda_task' AIRFLOW_CTX_EXECUTION_DATE='2024-08-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='backfill__2024-08-14T00:00:00+00:00'
[2024-08-16T09:48:02.160+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-16T09:48:02.189+0000] {logging_mixin.py:188} INFO - Data_Weather-20240814.csv
[2024-08-16T09:48:02.190+0000] {logging_mixin.py:188} INFO - 2024/08/14
[2024-08-16T09:48:02.190+0000] {logging_mixin.py:188} INFO - {"execution_date": "2024/08/14", "file_name": "Data_Weather-20240814.csv"}
[2024-08-16T09:48:02.191+0000] {logging_mixin.py:188} INFO - https://eyzyhdwl8l.execute-api.ap-southeast-2.amazonaws.com/dev?execution_date=2024/08/14&file_name=Data_Weather-20240814.csv
[2024-08-16T09:48:04.175+0000] {logging_mixin.py:188} INFO - Lambda function invoked successfully.
[2024-08-16T09:48:04.176+0000] {logging_mixin.py:188} INFO - Response: {'errorMessage': "Execution failed on sql 'SELECT * FROM SCD_CITY WHERE PROVINCE_CODE = 44 AND DBT_VALID_TO IS NULL ORDER BY CITY_CODE': 002003 (42S02): SQL compilation error:\nObject 'SCD_CITY' does not exist or not authorized.", 'errorType': 'DatabaseError', 'requestId': 'aa823f6c-abb2-48c9-b3fe-4406572875ad', 'stackTrace': ['  File "/var/task/lambda_function.py", line 108, in lambda_handler\n    result_df = extract_weather_data(file_name, execution_date)\n', '  File "/var/task/lambda_function.py", line 30, in extract_weather_data\n    result_set = pd.read_sql(query, con= conn)\n', '  File "/opt/python/pandas/io/sql.py", line 706, in read_sql\n    return pandas_sql.read_query(\n', '  File "/opt/python/pandas/io/sql.py", line 2738, in read_query\n    cursor = self.execute(sql, params)\n', '  File "/opt/python/pandas/io/sql.py", line 2686, in execute\n    raise ex from exc\n']}
[2024-08-16T09:48:04.180+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-08-16T09:48:04.182+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-16T09:48:04.198+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Weather_Data_Extraction, task_id=invoke_lambda_task, run_id=backfill__2024-08-14T00:00:00+00:00, execution_date=20240814T000000, start_date=20240816T094801, end_date=20240816T094804
[2024-08-16T09:48:04.253+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-08-16T09:48:04.298+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-08-16T09:48:04.301+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-08-16T10:12:25.624+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-16T10:12:25.832+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Weather_Data_Extraction.invoke_lambda_task backfill__2024-08-14T00:00:00+00:00 [queued]>
[2024-08-16T10:12:25.848+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Weather_Data_Extraction.invoke_lambda_task backfill__2024-08-14T00:00:00+00:00 [queued]>
[2024-08-16T10:12:25.849+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-08-16T10:12:25.873+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): invoke_lambda_task> on 2024-08-14 00:00:00+00:00
[2024-08-16T10:12:25.883+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2473) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-16T10:12:25.884+0000] {standard_task_runner.py:63} INFO - Started process 2477 to run task
[2024-08-16T10:12:25.885+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Weather_Data_Extraction', 'invoke_lambda_task', 'backfill__2024-08-14T00:00:00+00:00', '--job-id', '1283', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/Data_Weather_Extraction.py', '--cfg-path', '/tmp/tmp4dbuce8d']
[2024-08-16T10:12:25.888+0000] {standard_task_runner.py:91} INFO - Job 1283: Subtask invoke_lambda_task
[2024-08-16T10:12:25.937+0000] {task_command.py:426} INFO - Running <TaskInstance: Weather_Data_Extraction.invoke_lambda_task backfill__2024-08-14T00:00:00+00:00 [running]> on host ubuntu
[2024-08-16T10:12:26.056+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Ducky' AIRFLOW_CTX_DAG_ID='Weather_Data_Extraction' AIRFLOW_CTX_TASK_ID='invoke_lambda_task' AIRFLOW_CTX_EXECUTION_DATE='2024-08-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='backfill__2024-08-14T00:00:00+00:00'
[2024-08-16T10:12:26.059+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-16T10:12:26.098+0000] {logging_mixin.py:188} INFO - Data_Weather-20240814.csv
[2024-08-16T10:12:26.099+0000] {logging_mixin.py:188} INFO - 2024/08/14
[2024-08-16T10:12:26.099+0000] {logging_mixin.py:188} INFO - {"execution_date": "2024/08/14", "file_name": "Data_Weather-20240814.csv"}
[2024-08-16T10:12:26.100+0000] {logging_mixin.py:188} INFO - https://eyzyhdwl8l.execute-api.ap-southeast-2.amazonaws.com/dev?execution_date=2024/08/14&file_name=Data_Weather-20240814.csv
[2024-08-16T10:12:55.741+0000] {logging_mixin.py:188} INFO - Failed to invoke Lambda function.
[2024-08-16T10:12:55.742+0000] {logging_mixin.py:188} INFO - Response: {"message": "Endpoint request timed out"}
[2024-08-16T10:12:55.744+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-08-16T10:12:55.747+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-16T10:12:55.766+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Weather_Data_Extraction, task_id=invoke_lambda_task, run_id=backfill__2024-08-14T00:00:00+00:00, execution_date=20240814T000000, start_date=20240816T101225, end_date=20240816T101255
[2024-08-16T10:12:55.849+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-08-16T10:12:55.878+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-08-16T10:12:55.880+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
