[2024-08-13T16:06:46.557+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-13T16:06:46.619+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Weather_Data_Extraction.check_inserted backfill__2024-01-01T00:00:00+00:00 [queued]>
[2024-08-13T16:06:46.659+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Weather_Data_Extraction.check_inserted backfill__2024-01-01T00:00:00+00:00 [queued]>
[2024-08-13T16:06:46.660+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-08-13T16:06:47.081+0000] {taskinstance.py:2330} INFO - Executing <Task(BranchPythonOperator): check_inserted> on 2024-01-01 00:00:00+00:00
[2024-08-13T16:06:47.098+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=701) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-13T16:06:47.111+0000] {standard_task_runner.py:63} INFO - Started process 717 to run task
[2024-08-13T16:06:47.114+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Weather_Data_Extraction', 'check_inserted', 'backfill__2024-01-01T00:00:00+00:00', '--job-id', '90', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/Data_Weather_Extraction.py', '--cfg-path', '/tmp/tmpkoxwrgfn']
[2024-08-13T16:06:47.119+0000] {standard_task_runner.py:91} INFO - Job 90: Subtask check_inserted
[2024-08-13T16:06:47.153+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-08-13T16:06:47.252+0000] {task_command.py:426} INFO - Running <TaskInstance: Weather_Data_Extraction.check_inserted backfill__2024-01-01T00:00:00+00:00 [running]> on host ubuntu
[2024-08-13T16:06:47.503+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Ducky' AIRFLOW_CTX_DAG_ID='Weather_Data_Extraction' AIRFLOW_CTX_TASK_ID='check_inserted' AIRFLOW_CTX_EXECUTION_DATE='2024-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='backfill__2024-01-01T00:00:00+00:00'
[2024-08-13T16:06:47.508+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-13T16:06:47.543+0000] {baseoperator.py:400} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-08-13T16:06:47.547+0000] {logging_mixin.py:188} INFO - 2024-01-01
[2024-08-13T16:06:47.547+0000] {logging_mixin.py:188} INFO - <class 'pendulum.date.Date'>
[2024-08-13T16:06:47.610+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn_raw' for task execution.
[2024-08-13T16:06:47.612+0000] {connection.py:399} INFO - Snowflake Connector for Python Version: 3.10.1, Python Version: 3.12.4, Platform: Linux-5.15.153.1-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2024-08-13T16:06:47.615+0000] {connection.py:1239} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-08-13T16:06:48.708+0000] {logging_mixin.py:188} INFO - Connected Successfully!
[2024-08-13T16:06:48.710+0000] {logging_mixin.py:188} INFO - 
        SELECT MAX(INPUT_DATE) FROM RAW_WEATHER_DATA;
    
[2024-08-13T16:06:48.844+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-08-13T16:06:48.846+0000] {logging_mixin.py:188} INFO - No results found.
[2024-08-13T16:06:48.852+0000] {connection.py:762} INFO - closed
[2024-08-13T16:06:48.938+0000] {connection.py:768} INFO - No async queries seem to be running, deleting session
[2024-08-13T16:06:49.022+0000] {logging_mixin.py:188} INFO - invoke_lambda_task task will execute
[2024-08-13T16:06:49.024+0000] {python.py:237} INFO - Done. Returned value was: invoke_lambda_task
[2024-08-13T16:06:49.025+0000] {branch.py:36} INFO - Branch into invoke_lambda_task
[2024-08-13T16:06:49.026+0000] {skipmixin.py:178} INFO - Following branch invoke_lambda_task
[2024-08-13T16:06:49.058+0000] {skipmixin.py:246} INFO - Skipping tasks [('no_new_data', -1)]
[2024-08-13T16:06:49.100+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-13T16:06:49.134+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Weather_Data_Extraction, task_id=check_inserted, run_id=backfill__2024-01-01T00:00:00+00:00, execution_date=20240101T000000, start_date=20240813T160646, end_date=20240813T160649
[2024-08-13T16:06:49.187+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-08-13T16:06:49.241+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-08-13T16:06:49.247+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-08-14T02:44:45.102+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-14T02:44:45.121+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Weather_Data_Extraction.check_inserted backfill__2024-01-01T00:00:00+00:00 [queued]>
[2024-08-14T02:44:45.133+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Weather_Data_Extraction.check_inserted backfill__2024-01-01T00:00:00+00:00 [queued]>
[2024-08-14T02:44:45.133+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-08-14T02:44:45.373+0000] {taskinstance.py:2330} INFO - Executing <Task(BranchPythonOperator): check_inserted> on 2024-01-01 00:00:00+00:00
[2024-08-14T02:44:45.379+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=255) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-14T02:44:45.381+0000] {standard_task_runner.py:63} INFO - Started process 257 to run task
[2024-08-14T02:44:45.381+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Weather_Data_Extraction', 'check_inserted', 'backfill__2024-01-01T00:00:00+00:00', '--job-id', '324', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/Data_Weather_Extraction.py', '--cfg-path', '/tmp/tmpg38j278g']
[2024-08-14T02:44:45.384+0000] {standard_task_runner.py:91} INFO - Job 324: Subtask check_inserted
[2024-08-14T02:44:45.439+0000] {task_command.py:426} INFO - Running <TaskInstance: Weather_Data_Extraction.check_inserted backfill__2024-01-01T00:00:00+00:00 [running]> on host ubuntu
[2024-08-14T02:44:45.522+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Ducky' AIRFLOW_CTX_DAG_ID='Weather_Data_Extraction' AIRFLOW_CTX_TASK_ID='check_inserted' AIRFLOW_CTX_EXECUTION_DATE='2024-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='backfill__2024-01-01T00:00:00+00:00'
[2024-08-14T02:44:45.524+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-14T02:44:45.543+0000] {baseoperator.py:400} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-08-14T02:44:45.544+0000] {logging_mixin.py:188} INFO - 2024-01-01
[2024-08-14T02:44:45.544+0000] {logging_mixin.py:188} INFO - <class 'pendulum.date.Date'>
[2024-08-14T02:44:45.565+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn_raw' for task execution.
[2024-08-14T02:44:45.567+0000] {connection.py:399} INFO - Snowflake Connector for Python Version: 3.10.1, Python Version: 3.12.4, Platform: Linux-5.15.153.1-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2024-08-14T02:44:45.568+0000] {connection.py:1239} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-08-14T02:44:46.510+0000] {logging_mixin.py:188} INFO - Connected Successfully!
[2024-08-14T02:44:46.511+0000] {logging_mixin.py:188} INFO - 
        SELECT MAX(INPUT_DATE) FROM RAW_WEATHER_DATA;
    
[2024-08-14T02:44:46.750+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-08-14T02:44:46.752+0000] {logging_mixin.py:188} INFO - No results found.
[2024-08-14T02:44:46.752+0000] {connection.py:762} INFO - closed
[2024-08-14T02:44:46.835+0000] {connection.py:768} INFO - No async queries seem to be running, deleting session
[2024-08-14T02:44:46.932+0000] {logging_mixin.py:188} INFO - invoke_lambda_task task will execute
[2024-08-14T02:44:46.933+0000] {python.py:237} INFO - Done. Returned value was: invoke_lambda_task
[2024-08-14T02:44:46.934+0000] {branch.py:36} INFO - Branch into invoke_lambda_task
[2024-08-14T02:44:46.934+0000] {skipmixin.py:178} INFO - Following branch invoke_lambda_task
[2024-08-14T02:44:46.957+0000] {skipmixin.py:246} INFO - Skipping tasks [('no_new_data', -1)]
[2024-08-14T02:44:46.988+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-14T02:44:47.011+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Weather_Data_Extraction, task_id=check_inserted, run_id=backfill__2024-01-01T00:00:00+00:00, execution_date=20240101T000000, start_date=20240814T024445, end_date=20240814T024447
[2024-08-14T02:44:47.040+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-08-14T02:44:47.089+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-08-14T02:44:47.093+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
